[package]
name = "uefi_core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
RustBootServicesAllocatorDxe = { workspace = true }
r-efi = { workspace = true }
uefi_macro = { workspace = true }
