[build]
target = "x86_64-pc-windows-msvc"

[net]
git-fetch-with-cli = true

# [unstable]
# build-std-features = ["compiler-builtins-mem"]
# build-std = ["core", "compiler_builtins", "alloc"]
